// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARGCxCKmoJvpe9NE29tdSrltw3lc2k6uc',
    appId: '1:964220577716:web:6d9bb5f32bdea146a6b4e1',
    messagingSenderId: '964220577716',
    projectId: 'travel-app-1114d',
    authDomain: 'travel-app-1114d.firebaseapp.com',
    storageBucket: 'travel-app-1114d.firebasestorage.app',
    measurementId: 'G-7MS6T0PB7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA4FwMAD_GTtFX2a4tf10BB6CZTMG8avI',
    appId: '1:964220577716:android:e7d0f5150a830aaba6b4e1',
    messagingSenderId: '964220577716',
    projectId: 'travel-app-1114d',
    storageBucket: 'travel-app-1114d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJf9WGJoEv-lX3vIhnk9DP0P_9fbvcZ6M',
    appId: '1:964220577716:ios:402b26d9bf6f1367a6b4e1',
    messagingSenderId: '964220577716',
    projectId: 'travel-app-1114d',
    storageBucket: 'travel-app-1114d.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJf9WGJoEv-lX3vIhnk9DP0P_9fbvcZ6M',
    appId: '1:964220577716:ios:402b26d9bf6f1367a6b4e1',
    messagingSenderId: '964220577716',
    projectId: 'travel-app-1114d',
    storageBucket: 'travel-app-1114d.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARGCxCKmoJvpe9NE29tdSrltw3lc2k6uc',
    appId: '1:964220577716:web:3da348a40819b792a6b4e1',
    messagingSenderId: '964220577716',
    projectId: 'travel-app-1114d',
    authDomain: 'travel-app-1114d.firebaseapp.com',
    storageBucket: 'travel-app-1114d.firebasestorage.app',
    measurementId: 'G-4LNPPTSR56',
  );
}
